### ISSUE TITLE
Show bbox diagonal lines as mouse draging

### ISSUE THREAD

**Issue by jklhj222** [Ericsson/eva#10]
Hi,
I want to show the cross diagonal lines in the bbox during labeling process.
How to modify the code to achieve it.
thx

**Comment by manishs17** [comment]
Hi,  this file might help you get started with the feature you want.
[player.js](https://github.com/Ericsson/eva/blob/master/annotator/static/views/player.js)

we implemented drawCrosshairs , which gets called in the initPaper. You would also find the triggers on create bounds.

**Comment by jklhj222** [comment]
Thanks!
