### ISSUE TITLE
Docker file fails to build eva

### ISSUE THREAD

**Issue by jascase901** [Ericsson/eva#17]
see pull request  for fix https://github.com/Ericsson/eva/pull/16

steps to reproduce
* clone master
* docker-compose build

**Comment by jascase901** [comment]
I realized this actually fixes it because I was using llvmlite==0.31.0 and you guys were using llvmlite==0.32.0. Ill spend an hour or so looking into it.

**Comment by jascase901** [comment]
the real issue is 

https://pypi.org/project/llvmlite/
> 
> Compatibility
> 
> llvmlite works with Python 3.6 and greater.
> 
> As of version 0.33.0, llvmlite requires LLVM 9.0.x.
> 
> Historical compatibility table:

So  our options to fix this are to upgrade our python to 3.6m 

I tested changing the first line in the Dockerfile to this 
`FROM python:3.6-slim` and llvmlite built fine.

Or we could use version 0.31.0

**Comment by manishs17** [comment]
@jascase901 , I like the 2nd solution you suggested, i.e upgrade to python 3.6-slim in Dockerfile and just leave rest as it is. 
people who are not using Docker might need llvmlite in requirements.txt file.

**Comment by manishs17** [comment]
updated python in docker to 3.6-slim
