### ISSUE TITLE
Tracking for the next pages in a video

### ISSUE THREAD

**Issue by bedilbek** [Ericsson/eva#19]
How can I continue tracking for the next pages? Tracking stops after finishing for the current page

**Comment by manishs17** [comment]
In the settings [file](https://github.com/Ericsson/eva/blob/master/eva/settings.py), there are parameters
VIDEO_CHUNK_SIZE and TRACKER_SIZE, this defines how many images are tracked and displayed in one page.

*Tracking works good if you have smaller tracker_size if the object is moving around. If the object is completely static, then you can increase these number.

Hope that helps !

**Comment by bedilbek** [comment]
Thanks, I appreciate it! I was thinking of an interesting feature. Manual tracking on object selection, so that even if tracking is stopped after several numbers of images, we can just select that object and rerun the tracking. What do you think about it?

**Comment by manishs17** [comment]
@bedilbek , good thought ! but you can kind of achieve this now as well. 
Just try, if the tracking stops, displace and readjust the bbox, then press t on your keyboard again, the displaced bbox will be re-tracked. You can also lock the other annotations to be safe.

Also, when you move from one page to another, the latest tracking results are copied. e.g. you annotated images 1-100 in page 1, then when you move to page 2, the annotation bbox's from image-100 in page 1 are copied to image 101 in page 2. So from page 2, you can just readjust bbox and run the tracker again.

**Comment by bedilbek** [comment]
Ah, I didn't know about it. Great, thanks
