### ISSUE TITLE
Selected export for video frames

### ISSUE THREAD

**Issue by bedilbek** [Ericsson/eva#20]
What if I didn't annotate most of the frames from a video and I just want to download only those frames where there is an annotation?

**Comment by manishs17** [comment]
As of now it would export All, you can easily acheive this by puting in some logic in this [function](https://github.com/Ericsson/eva/blob/7862eda2803ffd8e0b4b3e984cacf0f81e959fb1/annotator/tasks.py#L211),  like if its empty don't export.  or even [here ](https://github.com/Ericsson/eva/blob/7862eda2803ffd8e0b4b3e984cacf0f81e959fb1/annotator/views.py#L152)

**Comment by bedilbek** [comment]
Great, thanks!
