### ISSUE TITLE
Cannot clone project

### ISSUE THREAD

**Issue by timurhamzin** [Ericsson/eva#22]
Hi! I haven't been able to download the project neither via shell nor through the link on github. Here's the shell log on my Windows 10 machine:
```git clone https://github.com/Ericsson/eva.git
Cloning into 'eva'...
remote: Enumerating objects: 3272, done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

**Comment by manishs17** [comment]
Probably not a repo issue, 

https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

**Comment by timurhamzin** [comment]
It was a git problem, solved it by using git-bash instead of Windows shell. Thank you.
