### ISSUE TITLE
Where are bbox annotations loaded from?

### ISSUE THREAD

**Issue by matthewlqin** [Ericsson/eva#32]
I'm trying to view the bbox data directly instead of exporting but can't figure out where the annotations are saved. 

From my understanding django loads them from an "annotation" folder but I can't find it

![image](https://user-images.githubusercontent.com/60992050/151653276-ce06b29a-9efe-473d-8036-0b323423b806.png)

Any advice would be greatly appreciated

**Comment by manishs17** [comment]
annotation/2/ is the URL , it calls [AnnotationView ](https://github.com/Ericsson/eva/blob/7862eda2803ffd8e0b4b3e984cacf0f81e959fb1/annotator/views.py#L138)in views.py,  if you follow that class you will see that it gets the annotation from the database. There are no folders called an annotation.

If required, you can log in to Django admin and see the data directly in the browser, or print it in the browser console.
