### ISSUE TITLE
Video Upload Error

### ISSUE THREAD

**Issue by zokatr** [Ericsson/eva#4]
![image](https://user-images.githubusercontent.com/24658159/75981283-42446b00-5ef5-11ea-9fa5-b2c466550a9b.png)

![image](https://user-images.githubusercontent.com/24658159/75982497-d7e0fa00-5ef7-11ea-978f-2542f3272d7c.png)

Hi, i have a problem like that when i try to upload videos but i can not find any solution. Can you help me ?

**Comment by manishs17** [comment]
hi @Gazi13 .

what python version are you using ? , please try with python 3.6.x ( don't use 3.6.7)

Let me know if the problem still persist.

**Comment by zokatr** [comment]
Let me try with 3.6. I'm using 3.7.0,  is this can be a problem ?

**Comment by manishs17** [comment]
celery might have issue, as async was renamed as asynchronous.

https://github.com/celery/celery/issues/4849

**Comment by zokatr** [comment]
For now i am not able to try 3.6 but i think the problem is about python version. 
@manishs17 
Thank you for your help.
