### ISSUE TITLE
Error while running manage.py

### ISSUE THREAD

**Issue by poornimajd** [Ericsson/eva#7]
Hi , Great work!
When I tried to install the setup on windows , I got the following error while running 
`python manage.py preparetracker`
Error:
`RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.`

Can someone please help me out?
Thank you

**Comment by manishs17** [comment]
Hi @poornimajd  , do you have a c++ compiler (msvc) installed in your pc ?
On windows, i would suggest you install Microsoft Visual Studio, I think community version should be fine as well. 
https://visualstudio.microsoft.com/downloads/

or
https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/

**Comment by poornimajd** [comment]
Thank you for the reply!Yes, I have Visual Studio installed on my Windows system,but it still throws the same error.

**Comment by poornimajd** [comment]
I solved it in ubuntu.

**Comment by manishs17** [comment]
@poornimajd  , that's nice . If you still want on windows just install 
Build Tools for Visual Studio 2019

you can find that in this page, 
https://visualstudio.microsoft.com/downloads/
scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.

**Comment by AbdurahmaanYuusuf** [comment]
> @poornimajd , that's nice . If you still want on windows just install
> Build Tools for Visual Studio 2019
> 
> you can find that in this page,
> https://visualstudio.microsoft.com/downloads/
> scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.

hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!

**Comment by manishs17** [comment]
> > @poornimajd , that's nice . If you still want on windows just install
> > Build Tools for Visual Studio 2019
> > you can find that in this page,
> > https://visualstudio.microsoft.com/downloads/
> > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> 
> hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!

what's the exact error message ?

**Comment by AbdurahmaanYuusuf** [comment]
> > > @poornimajd , that's nice . If you still want on windows just install
> > > Build Tools for Visual Studio 2019
> > > you can find that in this page,
> > > https://visualstudio.microsoft.com/downloads/
> > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > 
> > 
> > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> 
> what's the exact error message ?

python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python manage.py preparetracker
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by manishs17** [comment]
> > > > @poornimajd , that's nice . If you still want on windows just install
> > > > Build Tools for Visual Studio 2019
> > > > you can find that in this page,
> > > > https://visualstudio.microsoft.com/downloads/
> > > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > > 
> > > 
> > > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> > 
> > 
> > what's the exact error message ?
> 
> python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> 
> * python manage.py preparetracker
> * ```
>     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

what version of python you have installed ? use python 3.6 and try executing it from a separate command prompt terminal and not VS code.

**Comment by AbdurahmaanYuusuf** [comment]
> > > > > @poornimajd , that's nice . If you still want on windows just install
> > > > > Build Tools for Visual Studio 2019
> > > > > you can find that in this page,
> > > > > https://visualstudio.microsoft.com/downloads/
> > > > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > > > 
> > > > 
> > > > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> > > 
> > > 
> > > what's the exact error message ?
> > 
> > 
> > python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> > At line:1 char:1
> > 
> > * python manage.py preparetracker
> > * ```
> >     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
> >     + FullyQualifiedErrorId : CommandNotFoundException
> >   ```
> 
> what version of python you have installed ? use python 3.6 and try executing it from a separate command prompt terminal and not VS code.

i solved the python version problem . a am back to where i got stuck before.

RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.

**Comment by manishs17** [comment]
> > > > > > @poornimajd , that's nice . If you still want on windows just install
> > > > > > Build Tools for Visual Studio 2019
> > > > > > you can find that in this page,
> > > > > > https://visualstudio.microsoft.com/downloads/
> > > > > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > > > > 
> > > > > 
> > > > > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> > > > 
> > > > 
> > > > what's the exact error message ?
> > > 
> > > 
> > > python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> > > At line:1 char:1
> > > 
> > > * python manage.py preparetracker
> > > * ```
> > >     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
> > >     + FullyQualifiedErrorId : CommandNotFoundException
> > >   ```
> > 
> > 
> > what version of python you have installed ? use python 3.6 and try executing it from a separate command prompt terminal and not VS code.
> 
> i solved the python version problem . a am back to where i got stuck before.
> 
> RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.

have you installed this (Build Tools for Visual Studio 2019) from, https://visualstudio.microsoft.com/downloads/ 

if you have already done that, can you verify installtion by typing cl in Developer command prompt on windows
![image](https://user-images.githubusercontent.com/49199794/102207981-208a0280-3ecf-11eb-91cd-e862c05df14e.png)

**Comment by AbdurahmaanYuusuf** [comment]
> > > > > > > @poornimajd , that's nice . If you still want on windows just install
> > > > > > > Build Tools for Visual Studio 2019
> > > > > > > you can find that in this page,
> > > > > > > https://visualstudio.microsoft.com/downloads/
> > > > > > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > > > > > 
> > > > > > 
> > > > > > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> > > > > 
> > > > > 
> > > > > what's the exact error message ?
> > > > 
> > > > 
> > > > python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> > > > At line:1 char:1
> > > > 
> > > > * python manage.py preparetracker
> > > > * ```
> > > >     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
> > > >     + FullyQualifiedErrorId : CommandNotFoundException
> > > >   ```
> > > 
> > > 
> > > what version of python you have installed ? use python 3.6 and try executing it from a separate command prompt terminal and not VS code.
> > 
> > 
> > i solved the python version problem . a am back to where i got stuck before.
> > RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.
> 
> have you installed this (Build Tools for Visual Studio 2019) from, https://visualstudio.microsoft.com/downloads/
> 
> if you have already done that, can you verify installtion by typing cl in Developer command prompt on windows
> ![image](https://user-images.githubusercontent.com/49199794/102207981-208a0280-3ecf-11eb-91cd-e862c05df14e.png)

distutils.errors.LinkError: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\abdirahman\AppData\Local\Programs\Python\Python36\libs /LIBPATH:C:\Users\abdirahman\AppData\Local\Programs\Python\Python36\PCbuild\amd64 /LIBPATH:C:\\Users\\abdirahman\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 python36.lib msvcrt.lib npymath.lib /EXPORT:PyInit_fhog_utils C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\fhog_utils.cp36-win_amd64.o C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc\modulemixin.obj C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc\../_math_c99.obj C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc\../runtime/nrt.obj /OUT:C:\repos\eva\annotator\kcftracker\fhog_utils.cp36-win_amd64.pyd /IMPLIB:C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\fhog_utils.cp36-win_amd64.lib" failed with exit status 1158

this is the new error i got, it says distutils links error

**Comment by manishs17** [comment]
> > > > > > > > @poornimajd , that's nice . If you still want on windows just install
> > > > > > > > Build Tools for Visual Studio 2019
> > > > > > > > you can find that in this page,
> > > > > > > > https://visualstudio.microsoft.com/downloads/
> > > > > > > > scroll down until you see Tools for Visual Studio under the All downloads section and select the download for Build Tools for Visual Studio.
> > > > > > > 
> > > > > > > 
> > > > > > > hello i have done all what you suggested but i am still getting the error. please helpe me, it is quite urgent!!
> > > > > > 
> > > > > > 
> > > > > > what's the exact error message ?
> > > > > 
> > > > > 
> > > > > python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> > > > > At line:1 char:1
> > > > > 
> > > > > * python manage.py preparetracker
> > > > > * ```
> > > > >     + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
> > > > >     + FullyQualifiedErrorId : CommandNotFoundException
> > > > >   ```
> > > > 
> > > > 
> > > > what version of python you have installed ? use python 3.6 and try executing it from a separate command prompt terminal and not VS code.
> > > 
> > > 
> > > i solved the python version problem . a am back to where i got stuck before.
> > > RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.
> > 
> > 
> > have you installed this (Build Tools for Visual Studio 2019) from, https://visualstudio.microsoft.com/downloads/
> > if you have already done that, can you verify installtion by typing cl in Developer command prompt on windows
> > ![image](https://user-images.githubusercontent.com/49199794/102207981-208a0280-3ecf-11eb-91cd-e862c05df14e.png)
> 
> distutils.errors.LinkError: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\abdirahman\AppData\Local\Programs\Python\Python36\libs /LIBPATH:C:\Users\abdirahman\AppData\Local\Programs\Python\Python36\PCbuild\amd64 /LIBPATH:C:\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 python36.lib msvcrt.lib npymath.lib /EXPORT:PyInit_fhog_utils C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\fhog_utils.cp36-win_amd64.o C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc\modulemixin.obj C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc../_math_c99.obj C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\Users\abdirahman\AppData\Local\Programs\Python\Python36\lib\site-packages\numba\pycc../runtime/nrt.obj /OUT:C:\repos\eva\annotator\kcftracker\fhog_utils.cp36-win_amd64.pyd /IMPLIB:C:\Users\ABDIRA~1\AppData\Local\Temp\pycc-build-fhog_utils-z8kqzobo\fhog_utils.cp36-win_amd64.lib" failed with exit status 1158
> 
> this is the new error i got, it says distutils links error

check if this helps,  https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158
